# Dependencies
#markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Paula Pasqualini
tagline:          
description:      'I am a software engineer from São Paulo, Brazil.'
url:              https://pypas.github.io
baseurl:          /

author:
  name:           'Paula Pasqualini'
  url:            https://github.com/pypas

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pypas/pypas.github.io

kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
plugins: [jekyll-paginate]
paginate_path: "/projects/page:num/"